# This is a basic workflow to upload files 
# from GitHub to server via GitHub Actions
#derived from: https://github.com/milanmk/actions-file-deployer

name: Publish app

# Controls when the workflow will run
on:

  # Triggers the workflow on push request event 
  # but only for the specific branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs 
# that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "SFTP-Deploy-Action"
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action

    # The type of runner that the job will run on 
    # (depends on server but usually this value is works)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks 
    # that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:

          # Fetch all history for all tags and branches
          fetch-depth: 0

          # Checkout a specific branch
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run copy

      # This is a composite GitHub Action (Linux runner) 
      # for deploying repository content to remote server
      - name: SFTP-Deploy-Action
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          sync: full

          # Credentials for SFTP access to server using GitHub secrets
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}

          # Path for specific folder on server for files deployment
          local-path: ./dist
          remote-path: /

          # Port for SFTP access to server
          remote-port: 22